apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-private-registry
  name: docker-private-registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-private-registry
  template:
    metadata:
      labels:
        app: docker-private-registry
    spec:
      containers:
      - image: registry:2
        imagePullPolicy: IfNotPresent
        name: docker-private-registry
        env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:5000
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/cert.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/cert.key
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/registry
          name: image-store
        - mountPath: /certs
          name: certs
      volumes:
      - emptyDir: {} # THIS IS NOT PERSISTENT! WILL DELETE WITH POD!
        name: image-store
      - name: certs
        secret:
          secretName: registry-tls
          items:
          - key: tls.crt
            path: cert.crt
            mode: 256 # 0400 in decimal
          - key: tls.key
            path: cert.key
            mode: 256 # 0400 in decimal
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: docker-private-registry
  name: docker-private-registry
spec:
  ports:
  - nodePort: 30500
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: docker-private-registry
  type: NodePort

---
apiVersion: v1
kind: Secret
data:
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBNjMwdFNjdmQ5TnJBS2NYanVBUUFvUHlFWjY4R0cvc3ZWaDRTTU1NZjI2d1hVbmVrCmFHL1VDV1FKTkZyMzJhcnZRWHZ5RFRjeXNIYVA5SlFwTjh5N3hEM3NKTG5wYVBHYVYxR2o5MGZaZUw0Z3d3WEsKMUtGOWl1YnhpWXhBVVRJN2t3aXErN1M5K3NSbTR1WktER3FHbGk1TXJrUklSQ0dPM1VtL0FGRG0wR2ltcjVWSAptVnhMTHFJSXRDYWRyVnlBdjc3ZVhZWVNnQTJORE41TzUzbVlaKzdMbGtxNURnOEZtVHJQL240ejdJNDNaV0pQCnlTMTVuaUptZFVjb0hRQTZKaTMwWTJ1MklzSDNqdlhqa2I3TjFIUTVRcEx4T2l4Q2pSZkhEQXZvQkw5S3BHRVEKdWlBWkpxNnVhY1VxYm92ZXRIcDlpTUNPeTZYcmtEeEVwQlNubFFJREFRQUJBb0lCQVFEUUdDRENHcVk3N21acgpRNVRVa3F6ZmxlV0hIaEkrL2J1NTFQN3NHakYzMUY0VG9PZ201ZE13clRhNURqNEJHbDBzdDlPUXZCdE45cWVGClVMd1B0QnFrOHJkUFNQNHFuMzFzOWhiM3VJVkRmbmZDL3NaYkdZMndCaDZoRnMvck1JR1dqODFRZWtwN1k3MHIKZXFjcXk2Tzg2Sk1ZVi95b1FDTllCd2dDeG5zQTVCZUFSK2tFTlNGbHVtWjFVOTVBSVRUT2llTXNwaHI2VnpmKwpZLzNPK0ZZak14NHhQVVJpMXNHMTRRT3R1QUhadDdMN2lRcDRaV01rWVZuTTNSUnhqNnFCL3pCT3JrUXdtNFdnCm85UWpMMVhJUjJGZ3oxTnNaendKSUx4eW9UYzJyV290elgxSkoyS01CSkdiaWIvSUJHM0NiczNrZytFaG9ZTVgKYkVrRVRhK0JBb0dCQU8vVUNVd1V6L0hxbGZMY1ZwaXdUTGVLT2VUNFkweVFPNlpBOEJzTHJDN1ZsbVkrdTl2bQpYa3orVjZQZFhBQUJzQngyT3pjcGhyTEtWb3A3eVJWNDFETkNzRm1VZEk5NTBrRFkxM1NzWmNyRlFPcDd2dkNrCmcyN1F3NjNBaGdKUWFkQmZqMHIwcXlYN0NJWlF1RDJGTUt1TWV1NlJXT3Z1N1lMRTBwSEdMRkcxQW9HQkFQdGUKUEJ6cS8rK0l5U01lWnFBTVUrbndZcWFmNnRvZ21CRlNvM2N3ejVoNWNzWjFDQXJwRG9RQ0RXM2Q0Zlp5d04vUQpmUGFBSGVaNVl6eGpNdGNiemt2Q3BORWo5WFJDMFNpaEloT2NFcHFFbjdQVG84dnBleWRBNkNpS0dIcXVtUXRmCmFPU25hc2FBRm1TUm0yemJlYVlRMWxHaTFISk1Fb2pBQjFROW1pcGhBb0dBYUlDZlVIeWRJOC9SYVJMajFRSzEKV3lDckczKzBYUzlZSHBpYlIxMnR1SGF2WTN3Z2hiQjdGTmViUHJiOUdLK2ptck5XR0RKTEZHc2dqSlZseUtwdQo1S3RCaHJjdWx6cEJDS3EwTDQzVGlTaXNvY0FzTWxXdFE4TktFTk1jVWJQU2Q4Njc5TEJxUjFGOHBISlY1ZEM4CnBYUEFPV1l5TmhSVmdDN2RobEd4RENVQ2dZRUF0dTVYZFB3WWtldkw1UURrMHFqbUVLUGVSMEN1RzF3SkR1SkQKRUNTM2oxRWpGQVpyZWZVdG1TZ2RPYzExK25KOHB1VUZiQ2JFbTh2UFNrMHUzSmpod3dTK0NXM1AzWElhNFNTUwp0ZzZwQTBadEt1TmttcXNwOHVFcmt3VWMxM3RrNlgvZnlEZUdYenNzRUxoZWtoUVBMYW1uTHZYL0FjY1czZXBSCjZ4NkJxVUVDZ1lFQXZ2RkJjdy9GcXdDdld3OWJ5NXVLUWR0eUxWeTZ6cHRucDdMQkNCMXU3K0F5eElmT2MxVjQKbUNyZHlGelYxMExPTUtDTHFsVzd4L1ZreDUwTFdMR3R5d3daSXRYR2FDSmp1MDhCdzh3ZnZacjZoUWM3OWxHWgpoSlIySW5IVkJ0cEdielRSc2l2VmRsZ1dPTk9CM0dvSFE0UUFkck1Sd0VoOWR4UE44WWJ0UVZrPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo= 
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoekNDQW0rZ0F3SUJBZ0lVU0JDSUVJTmMwMlNvZHMxblltaStJVG9Ua3FNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF4TUthM1ZpWlhKdVpYUmxjekFlRncweU1ERXhNVEl4T0RFMk1EQmFGdzB5TVRFeApNVEl4T0RFMk1EQmFNR014Q3pBSkJnTlZCQVlUQWxWVE1SVXdFd1lEVlFRSUV3eFFaVzV1YzNsc2RtRnVhV0V4CkV6QVJCZ05WQkFjVENraGhjbkpwYzJKMWNtY3hFekFSQmdOVkJBb1RDa3QxWW1WeWJtVjBaWE14RXpBUkJnTlYKQkFzVENtdDFZbVZ5Ym1WMFpYTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEcgpmUzFKeTkzMDJzQXB4ZU80QkFDZy9JUm5yd1liK3k5V0hoSXd3eC9ickJkU2Q2Um9iOVFKWkFrMFd2ZlpxdTlCCmUvSU5Oekt3ZG8vMGxDazN6THZFUGV3a3VlbG84WnBYVWFQM1I5bDR2aUREQmNyVW9YMks1dkdKakVCUk1qdVQKQ0tyN3RMMzZ4R2JpNWtvTWFvYVdMa3l1UkVoRUlZN2RTYjhBVU9iUWFLYXZsVWVaWEVzdW9naTBKcDJ0WElDLwp2dDVkaGhLQURZME0zazduZVpobjdzdVdTcmtPRHdXWk9zLytmalBzampkbFlrL0pMWG1lSW1aMVJ5Z2RBRG9tCkxmUmphN1lpd2ZlTzllT1J2czNVZERsQ2t2RTZMRUtORjhjTUMrZ0V2MHFrWVJDNklCa21ycTVweFNwdWk5NjAKZW4ySXdJN0xwZXVRUEVTa0ZLZVZBZ01CQUFHamdZQXdmakFPQmdOVkhROEJBZjhFQkFNQ0JhQXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFCkZQaWIzb0tDVnRxYzJ5Z0xDREFsTGZCemVvUGRNQ0FHQTFVZEVRUVpNQmVDQ1d4dlkyRnNhRzl6ZEljRWZ3QUEKQVljRUNoR0NJakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBeEFBaGJVUjJXSXl4YU9va29kMG9lVndCeUZDWApOSkRtUkZpL1RFMEJyd292NTBWMmtzVzBkdS9KR05JWXEwOG9ONmxTWlBwZDBJdXlBZmZQclFSRmJyYW1CMTJZCjg4Z3ZVYVlVNHIzRXZRM3FBZFlaQ205N1NiZjlCVTN4aCs3SUQzOXdZb2E1cnZpT2p4elhiL08wQm1RcFdLbDIKQUdPNHllZzhBZ3c1SXB6WXZBbkQ0WFhuTHg2RXVzckduUFNPeFhRQ2FOazFncUhvZXdWVnhrb1NGQWYvb05zRQpPbU9RbDFzMXdFNDkrb2Y5QXJ2cGZtazRPWm80Zll2RzVseU9SM0N4dlNUclZ1cWZvd1FPRVZESHArT01TOHRDCk5qbVRMdjlsVWlyaDN1Q3FoODV2UjFMK3k1MWVyRXpVNlNUUkZkTUo4OENBdkZqVldqMi9ISWkxV1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
metadata:
  name: registry-tls
  namespace: default
type: Opaque
