apiVersion: v1
kind: Pod
metadata:   
  name: menu
  labels:
    dragon: menu
spec:
  containers:
  - image: 10.17.130.34:30500/menu
    name: menu
    ports:
    - containerPort: 2227
---
apiVersion: v1
kind: Pod
metadata:
  name: login
  labels:
    dragon: login
spec:
  containers:
  - image: 10.17.130.34:30500/login
    name: login
    ports:
    - containerPort: 2228 
    
---
apiVersion: v1
kind: Pod
metadata:
  name: fortune
  labels:
    dragon: fortune
spec:
  containers:
  - image: 10.17.130.34:30500/fortune_cookie
    name: fortune
    ports:
    - containerPort: 2229

---
apiVersion: v1
kind: Pod
metadata:
 name: api-gateway
 labels:
   dragon: api-gateway
spec:
 containers:
 - image: 10.17.130.34:30500/api_gateway
   name: api-gateway
   ports:
   - containerPort: 2225
